"use client";
import {useState} from "react";

type Preflight={token:string;year:string;datasetType:string;fileName:string;fileSize:number;sha256:string;checks:{label:string;status:string;detail:string}[]};

export default function DataIntakeDialog({onClose}:{onClose:()=>void}){
  const[file,setFile]=useState<File|null>(null),[result,setResult]=useState<Preflight|null>(null),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState("请选择年度数据文件");
  const step=result?3:file?2:1;
  async function preflight(form:HTMLFormElement){if(!file)return;setBusy(true);setMessage("正在隔离预检文件…");try{const response=await fetch("/api/data-upload",{method:"POST",body:new FormData(form)}),data=await response.json();if(!response.ok)throw new Error(data.error||"预检失败");setResult(data);setMessage("基础预检完成，请核对校验结果")}catch(error){setMessage(error instanceof Error?error.message:"预检失败")}finally{setBusy(false)}}
  return <div className="detailBackdrop uploadBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="dataWorkbench"><header><div><span>DATA MANAGEMENT</span><h2>年度数据安全接入</h2><p>新数据先进入隔离预检区，确认差异并备份后才允许替换正式数据。</p></div><button onClick={onClose}>×</button></header><div className="intakeSteps">{["上传文件","隔离预检","差异确认","正式入库"].map((label,index)=><div key={label} className={step>index?"active":""}><b>{index+1}</b><span>{label}</span></div>)}</div><form onSubmit={e=>{e.preventDefault();preflight(e.currentTarget)}}><div className="intakeMain"><section className="intakeCard"><h3>上传并预检新版数据</h3><div className="intakeSelectors"><label>数据年度<select name="year" defaultValue="2025"><option>2025</option><option>2026</option><option>2027</option></select></label><label>更新类型<select name="datasetType"><option value="housing-safety">完整年度数据</option><option value="incremental">年度增量数据</option><option value="correction">历史数据修订</option></select></label></div><label className="dropZone"><input required name="file" type="file" accept=".xlsx,.xls,.csv,.json" onChange={e=>{const next=e.target.files?.[0]||null;setFile(next);setResult(null);setConfirmed(false);setMessage(next?"文件已选择，可以开始预检":"请选择年度数据文件")}}/><b>⇧</b><strong>{file?.name||"选择年度数据文件"}</strong><small>{file?`${(file.size/1024/1024).toFixed(2)} MB`:`支持 XLSX、XLS、CSV、JSON，最大 50MB`}</small></label><button className="preflightButton" disabled={!file||busy}>{busy?"正在预检…":"开始预检并比较差异"}</button><p className="intakeMessage">{message}</p></section><aside className="safetyCard"><h3>数据安全机制</h3><ol><li>上传文件与正式数据库隔离</li><li>校验行政区、年度和指标口径</li><li>展示新增、变化、缺失和异常</li><li>人工确认后自动备份再入库</li><li>记录文件哈希、批次和操作时间</li></ol><em>预检阶段不会修改当前数据库</em></aside></div>{result&&<div className="preflightResult"><section><div className="resultHead"><div><span>预检结果</span><h3>{result.fileName}</h3></div><small>SHA-256 {result.sha256.slice(0,16)}…</small></div><div className="checkGrid">{result.checks.map(check=><article key={check.label} className={check.status}><b>{check.status==="passed"?"✓":"○"}</b><div><strong>{check.label}</strong><small>{check.detail}</small></div></article>)}</div></section><section className="confirmImport"><h3>差异确认与正式入库</h3><p>当前已完成通用文件预检。待真实年度数据模板确定后，将在这里展示逐项差异、质量问题和模拟数据替换范围。</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已核对预检信息并理解正式入库会替换该年度模拟数据</label><button type="button" disabled={!confirmed}>确认并正式入库（模板确定后启用）</button></section></div>}</form><footer><span>建议保留每次成功导入的源文件、质量报告、数据库备份和批次记录</span><button onClick={onClose}>关闭</button></footer></section></div>;
}
